title: KGrid Documentation
author: KGrid Development Team
email: dlhs.knowledge.grid@umich.edu
multipage: false
description: > # this means to ignore newlines until "baseurl:"
  Knowledge Grid Documents Cover Page

#github_username:  kgrid-um-team

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - smart.md
#   - DEMO-L1.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock


google_analytics: UA-133554011-1

