title: KGRID REPO DOCUMENTATION
author: KGrid Development Team
email: dlhs.knowledge.grid@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Knowledge Grid Documents Cover Page

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
