title: KGrid Getting Started Guides
author: KGrid Development Team
email: dlhs.knowledge.grid@umich.edu
multipage: true
description: > # this means to ignore newlines until "baseurl:"
  Knowledge Grid Getting Started Guides for different KGrid personnas