title: KGRID REPO DOCUMENTATION
author: KGrid Development Team
email: dlhs.knowledge.grid@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  PostPCI Risks App calculates the risks in 12-30 months after the procedure with pateint data from SMART sandbox


#github_username:  kgrid-um-team

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#  - getting_started.md
#  - activator_checklist.md

theme: minima
